os:
  osx
sudo: false
language: generic
cache:
  directories:
  - "$HOME/.stack"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal build --copy-bins --local-bin-path .
- stack --no-terminal test